### ISSUE TITLE
HTML Degree

### ISSUE THREAD

**Issue by archergod** [prairiewest/PHPconvertDMSToDecimal#3]
Hi, 

If we have degree symbol in HTML then we need to add 

 `$latlng = str_replace("&deg;"," ",$latlng);`

feeling lazy to create pull request just for this small thing :). Hope you don't mind.

**Comment by prairiewest** [comment]
If the input is HTML encoded then the programmer can decode it before passing to this function.  I don't agree with including this.

**Comment by archergod** [comment]
Well choice is yours, but I don't understand when you are using all other degree symbol, why embedding is not desirable. Yes programmer can decode it, but another bit of one line solve a good issue is not much. Anyway, thanks for your code. It is great help.
