### ISSUE TITLE
Package name should be lowercase

### ISSUE THREAD

**Issue by dotherightthing** [prairiewest/PHPconvertDMSToDecimal#9]
> Deprecation warning: `require.prairiewest/PHPconvertDMSToDecimal` is invalid, it should not contain uppercase characters. Please use `prairiewest/phpconvertdmstodecimal` instead. Make sure you fix this as Composer 2.0 will error.

After receiving the following warning, I ignored the real / CamelCase package name and used all lowercase in my `composer.json`. This works in my local dev environment (MAMP running on MacOS, which is case insensitive) but fails on my live server (Linux/Ubuntu, which is case sensitive).

It seems that this is because `vendor/composer/autoload_files.php` still references the CamelCase version: 

> return array(
>     '0dde8757f8ded8a837c699d6cdc5452a' => $vendorDir . '/prairiewest/PHPconvertDMSToDecimal/convert.php',
> );

Can you please rename the package, so that the name is all lowercase? `/prairiewest/phpconvertdmstodecimal`

**Comment by dotherightthing** [comment]
I should note that my use case is a bit different from a standard Composer install, as I am using Node to copy `require` directories into a release folder for distribution via Github releases. Regardless, this wouldn't be an issue if the package name was lowercase.

**Comment by prairiewest** [comment]
Done
